<?php
namespace MartinsHumberto\PagarmeGateway\Rules\Subscription;

class CreatePlanSubscriptionValidation
{
    protected static $validations = [
        'stable' => [
            'code' => 'nullable|string|max:52',
            'plan_id' => 'required|string',
            'payment_method' => 'required|string|in:credit_card,boleto,debit_card',
            'start_at' => 'nullable|date',
            'customer_id' => 'required_without:customer',
            'customer' => 'required_without:customer_id|array',
            'customer.name' => 'required|max:64',
            'customer.email' => 'nullable|email|max:64',
            'customer.document' => 'nullable|max:50',
            'customer.document_type' => 'nullable|in:CPF,CNPJ,PASSPORT',
            'customer.type' => 'required_with:customer.document|in:individual,company',
            'customer.gender' => 'nullable|string|in:male,female',
            'customer.address' => 'nullable|array',
            'customer.address.country' => 'required_with:customer.address|size:2',
            'customer.address.state' => 'required_with:customer.address|size:2',
            'customer.address.city' => 'required_with:customer.address|string',
            'customer.address.zip_code' => 'required_with:customer.address|string',
            'customer.address.line_1' => 'required_with:customer.address|string',
            'customer.address.line_2' => 'required_with:customer.address|string',
            'customer.phones' => 'nullable|array',
            'customer.phones.mobile_phone' => 'nullable|array',
            'customer.phones.mobile_phone.country_code' => 'required_with:customer.phones.mobile_phone|string',
            'customer.phones.mobile_phone.area_code' => 'required_with:customer.phones.mobile_phone|string',
            'customer.phones.mobile_phone.number' => 'required_with:customer.phones.mobile_phone|string',
            'customer.birthday' => 'nullable|date',
            'customer.metadata' => 'nullable',
            'card_id' => 'nullable',
            'card_token' => 'nullable',
            'card' => 'nullable|array',
            'card.number' => 'nullable|between:13,19',
            'card.holder_name' => 'nullable|max:64|regex:/[a-zA-Z]+/',
            'card.holder_document' => 'nullable|between:11,14',
            'card.exp_month' => 'nullable|between:1,12',
            'card.exp_year' => 'nullable|date_format:Y',
            'card.cvv' => 'nullable|between:3,4',
            'card.label' => 'nullable',
            'card.billing_address_id' => 'nullable|max:36',
            'card.billing_address' => 'nullable|array',
            'card.billing_address.line_1' => 'nullable|max:256',
            'card.billing_address.line_2' => 'nullable|max:128',
            'card.billing_address.country' => 'nullable|size:2',
            'card.billing_address.state' => 'nullable|size:2',
            'card.billing_address.city' => 'nullable',
            'card.billing_address.street' => 'nullable',
            'card.billing_address.zipcode' => 'nullable|size:8',
            'card.billing_address.neighborhood' => 'nullable',
            'card.billing_address.street_number' => 'nullable',
            'card.billing_address.complementary' => 'nullable',
            'discounts' => 'nullable|array',
            'discounts.*.cycles' => 'required_with:discounts|string',
            'discounts.*.value' => 'required_with:discounts|string',
            'discounts.*.discount_type' => 'required_with:discounts|string|in:flat,percentage',
            'increments' => 'nullable|array',
            'increments.*.cycles' => 'required_with:increments|string',
            'increments.*.value' => 'required_with:increments|integer',
            'increments.*.increment_type' => 'required_with:increments|string|in:flat,percentage',
            'gateway_affiliation_id' => 'nullable|string',
            'boleto_due_days' => 'nullable|integer',
            'metadata' => 'nullable',
            'split' => 'nullable|array',
            'split.enabled' => 'nullable|boolean',
            'split.rules' => 'nullable|array',
            'split.rules.*.amount' => 'nullable|string',
            'split.rules.*.type' => 'nullable|string|in:flat,percentage',
            'split.rules.*.recipient_id' => 'nullable|string',
            'split.rules.*.options' => 'nullable|array',
            'split.rules.*.options.charge_processing_fee' => 'required_with:split.rules.*.options|boolean',
            'split.rules.*.options.charge_remainder_fee' => 'required_with:split.rules.*.options|boolean',
            'split.rules.*.options.liable' => 'required_with:split.rules.*.options|boolean',
        ]
    ];

    public static function rules(string $version)
    {
        return self::$validations[$version];
    }
}
